-- Add extended columns to business_services for fleet asset management
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS asset_class text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS sub_category text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS year_make_model text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS length_ft text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS payload_capacity text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS empty_weight text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS dimensions text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS hitch_connection text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS ball_size text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS electrical_plug text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS traction_type text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS axle_configuration text;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS daily_rate numeric;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS three_day_rate numeric;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS weekly_rate numeric;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS monthly_rate numeric;
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS features text[];
ALTER TABLE public.business_services ADD COLUMN IF NOT EXISTS youtube_url text;